[colors]
background = "black"
foreground = "white"
cursor = "yellow"
selection = "cyan"

[style]
directory = { fg = "cyan", bold = true }
executable = { fg = "green", bold = true }
symlink = { fg = "magenta" }
fifo = { fg = "yellow" }
socket = { fg = "red" }
